name: Docker-Staging

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare tags
        id: prep
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            BRANCH="master"
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            BRANCH="build-test"
          fi
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=branch::${BRANCH}
      - name: Prepare docker build env
        id: dockerPrep
        run: |
          NEXT_PUBLIC_MATOMO_URL="https://analytics.desmos.network"
          NEXT_PUBLIC_MATOMO_SITE_ID=11
          NEXT_PUBLIC_URL="https://desmos.network/"
          echo ::set-output name=NEXT_PUBLIC_MATOMO_URL::${NEXT_PUBLIC_MATOMO_URL}
          echo ::set-output name=NEXT_PUBLIC_MATOMO_SITE_ID::${NEXT_PUBLIC_MATOMO_SITE_ID}
          echo ::set-output name=NEXT_PUBLIC_URL::${NEXT_PUBLIC_URL}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            "NEXT_PUBLIC_MATOMO_URL=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_MATOMO_URL }}"
            "NEXT_PUBLIC_MATOMO_SITE_ID=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_MATOMO_SITE_ID }}"
            "NEXT_PUBLIC_URL=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_URL }}"
          tags: "desmoslabs/desmos-landing:${{ steps.prep.outputs.branch }}-staging"
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
